- name: Playbook for creating users
  hosts: servers
  become: yes
  vars_files:
  - users.yml

  tasks:
  - name: Add users
    user:
      name: "{{ item.name|lower }}"
      create_home: yes
      comment: "{{ item.name|lower }}@{{ domain_name }}"
      password: "{{ item.password | password_hash('sha512')}}"
      update_password: on_create
    loop: "{{ users }}"